


services:  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    image: node:18-alpine
    working_dir: /usr/src/app
    command: npm run dev --prefix src/frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend



